name: Convert XCArchive to IPA

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Archive (if using GitHub Releases)
        run: wget -O build.xcarchive.zip "https://github.com/YOUR_USERNAME/YOUR_REPO/releases/download/YOUR_TAG/build.xcarchive.zip"

      - name: Unzip Archive
        run: unzip build.xcarchive.zip

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build.xcarchive \
            -exportPath output_folder \
            -exportOptionsPlist exportOptions.plist

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exported-ipa
          path: output_folder/*.ipa
